### ISSUE TITLE
DocumentByLine viewlet not displayed for authenticated members

### ISSUE THREAD

**Issue by cekk** [plone/plone.app.layout#130]
On Plone 5.1 with last p.a.layout version.

According to [this line of code](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/content.py#L74) the DocumentByLine viewlet is displayed only if the user is Anonymous and allow_anon_views_about == True.

I can fix it directly on this repo, but i don't know if it's some design choice or a bug ;)

**Comment by pbauer** [comment]
I think that might be a design-choice since the toolbar holds that information for logged-in users.

**Comment by cekk** [comment]
Damn toolbar ;)
Ok, this makes sense, but for me is a bit strange that anonymous and authenticated see the same information in different places.

btw: ok, let's keep it like this..i'll fix it in my theme. Thanks!
