### ISSUE TITLE
Should we add an id to analytics viewlet rendering?

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.layout#157]
This would make it easier for Diazo themes implementations. Some solutions [suggested by the community](https://stackoverflow.com/questions/12940552/diazo-ignores-the-javascript-for-web-statistics/12949084) involves adding an id to the script tag, but this solution IMHO is too much error prone (specially because official docs like https://developers.google.com/analytics/devguides/collection/analyticsjs/ are literally copy and paste for users).

In a nutshell: this

https://github.com/plone/plone.app.layout/blob/34d7d071cc6d8d6e7eb00895f078d1eaef2ad1c4/plone/app/layout/analytics/view.py#L31

would become

```python
return '<div id="plone.analytics">{0}</div>'.format(site_settings.webstats_js)
```

We would make a PR for this really simple suggestion, but we stil can't have a contributor's agreement because of some internal legal issues.

I know everyone is into Plone 5, but if someone decides to implement it would be very nice to be backported to Plone 4 as well.

**Comment by erral** [comment]
@laulaz @idgserpro we have faced this for Diazo theming too. I have prepared PRs for Plone 4.3, 5.0, 5.1 and 5.2. 

Can you review them please?
