### ISSUE TITLE
IBodyClassAdapters miss template and view

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.layout#158]
I was very excited to find the new IBodyClassAdapter so I can remove monkeypatch overrides for bodyClass .  From the design discussion in #127 I read that template and view deliberately were not passed to the Adapter, but my use case is exactly needing those and it is very cumbersome to fetch these somewhere from the context and request as they are injected into bodyClass from the main_template call. 

Actually I don't really need template and/or view in the following use case but the calculated 'name' at the top of the default bodyClass, with template / view I could redo those calculations. 

My use case is adding a 'controlpanel' class when a control panel item/form is views. The difficulty is that you can never be sure in Plone if you are on a control panel because not all control panels use the controlpanel formwrappers and some panels like dexterity and the registry started as add'ons and were added to core later. The trick is to query the control_panel actions (cache that query) and see if the view name is one of the actions. 
```
        @ram.cache(lambda *args: time() // (60 * 10))
        def control_panel_views():
            """ Fetch al control panel view names so we can match them """
            pctool = getToolByName(self.context, 'portal_controlpanel')
            actions = []
            groups = [g['id'] for g in pctool.getGroups()]
            for group in groups:
                actions.extend(
                    [a['url'] for a in pctool.enumConfiglets(group=group)])
            # strip path and @@ in view name
            actions = map(lambda a: a.split('/')[-1], actions)
            actions = map(lambda a: a.replace('@@', ''), actions)

            # manual stuff where the view name is not the url view name
            # dexterity_types has 'edit', lets not match that...
            actions.append('configuration_registry')
            return actions
```
@thet what was the original argument to not include template and view?  cc: @jensens @agitator 

Or I could add this to the core Plone LayoutPolicy if it is useful enough, then I don't need to write a BodyClassAdapter, but it still feels hackish and overhead to periodically query the control panel actions and add hardcoded exceptions ;-)

**Comment by jensens** [comment]
I think passing ``template`` and ``view`` to ``get_classes`` here does not hurt and may help a view. https://github.com/plone/plone.app.layout/blob/f66688025339ad25f58343b247a798868761c91f/plone/app/layout/globals/layout.py#L324
So +1 for a PR.

**Comment by jensens** [comment]
btw., the major problem here here is to not break existing adapters

**Comment by fredvd** [comment]
> btw., the major problem here here is to not break existing custom adapters

It will be quite difficult not to break existing adapters, but this has been merged for only 3-4 months and the only use case I have seen so far are the mosaic body classes by  @agigator , that's actually how I found out about the IBodyClassAdapter. :-) 

It's either passing in arguments to the get_classes which is also very similar to the orginal bodyCass(template, view) call in main_template, or extending the adapter itself with two more parameters on the __init__  but 4  might get confusing.

**Comment by jensens** [comment]
Well, adapting 4 things here is IMO bad style.
It seems that it's public usage is limited to mosaic https://github.com/search?q=IBodyClassAdapter&type=Code
I know @thet used it in a customer project.
I would really not like to break those. 

In order to not do so, we could simple introduce a new method (i.e. "classes", I don't like the ``get``prefix anyway). If it does not exists we fallback to  call ``get_classes`` if it exist w/o those parameters and propagate a DeprecationWarning. This is - after 3-4 month - not very common, but imo at least a clean way to tackle the problem.

**Comment by mauritsvanrees** [comment]
We could first call `get_classes(template, view)`, catch a `TypeError`, and then fall back to calling `get_classes` without arguments.

**Comment by jensens** [comment]
+1 given that the second call issues a depreciation warning.

**Comment by thet** [comment]
+1, sounds good. I'm not too concerned with updating my codebase, if someone pings me to do so, though.

**Comment by rodfersou** [comment]
https://github.com/plone/plone.app.layout/pull/165/files
https://github.com/plone/plone.app.layout/pull/166/files

**Comment by rodfersou** [comment]
Fixed in:
https://github.com/plone/plone.app.layout/pull/165/files
https://github.com/plone/plone.app.layout/pull/166/files
https://github.com/plone/plone.app.layout/pull/167/files
https://github.com/plone/plone.app.layout/pull/168/files
https://github.com/plone/plone.app.layout/pull/171/files

**Comment by rodfersou** [comment]
A new release would be appreciated!
