### ISSUE TITLE
Document byline is only shown for anonymous users

### ISSUE THREAD

**Issue by erral** [plone/plone.app.layout#160]
As per https://github.com/plone/plone.app.layout/commit/1845be16f68cec3fea635032212259d8dac6de58 document byline is only shown for anonymous users, and only when the "show about information" option is enabled in Plone settings.

Why are we hiding the byline for logged-in users? 

It even conflicts with the message shown on the "show about information" check in Plone settings, where says _Allow anyone to view 'about' information **If not selected only logged-in users will be able to view** information about who created an item and when it was modified._

@hvelarde

**Comment by hvelarde** [comment]
long story… I just give up arguing about the change on the byline years ago, you can read it here: https://github.com/plone/Products.CMFPlone/issues/668#issuecomment-122274321

it seems to be still broken and I want it also back.

**Comment by hvelarde** [comment]
no, please, we need to fix it; now that we're going to start using Plone 5.1 we need the document byline visible.

what's different among Plone 5.0 and Plone 5.1?

**Comment by erral** [comment]
They use different versions of plone.app.layout. In Plone 5.0, the byline is shown for logged-in users and for anonymous if the "show about information" check is enabled. In Plone 5.1, the byline is shown only for anonymous users if the "show about information" check is enabled.

Plone 5.0.x uses plone.app.layout 2.5.x: https://github.com/plone/plone.app.layout/blob/2.5.x/plone/app/layout/viewlets/content.py#L78

Plone 5.1.x uses plone.app.layout 2.7.x:
https://github.com/plone/plone.app.layout/blob/2.7.x/plone/app/layout/viewlets/content.py#L74

**Comment by hvelarde** [comment]
ok, that's a regression then; in Plone 5.1 it should work the same as in Plone 5.0.

**Comment by erral** [comment]
I can prepare a PR for both 2.7 branch and master.

**Comment by erral** [comment]
PRs ready to be reviewed
