### ISSUE TITLE
Navigation opener action acts weirdly because of missing unique identifier UID

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.layout#184]
<img width="779" alt="screenshot 2019-02-20 at 18 13 29" src="https://user-images.githubusercontent.com/365761/53110474-45172c80-353b-11e9-8de0-9e6c2cf4bb25.png">

@ale-rt I found a logic error for the integration of the portal_tabs in the markup.

First we get the portal_tabs, which include the main navigation items as well and after that the dict is extended with the items of the catalog. The portal_tabs don't include review state or a UID.
Therefore the opener doesn't get the unique identifier needed to work as input/label combo.

What do you think is the best way to fix this? Getting the portal_tabs directly, so only the manually defined actions are pulled from there or do you see a way to easily update those entries in the dict? 

One more detail, the opener input/label combo is doubled in the markup, 
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/navigation/navtree.py#L379 can imho be removed.

**Comment by ale-rt** [comment]
Will check that

**Comment by agitator** [comment]
one more thing...
In pre5.2 we marked the main tabs with id="portaltab-index_html", id="portaltab-news"
should we readd this as well? what do you think?

**Comment by ale-rt** [comment]
Fine for me, if you have time please do that!

**Comment by ale-rt** [comment]
@agitator this should be fixed by #185. Can you please review it? Thanks!
