### ISSUE TITLE
Update markup of templates to Bootstrap 4

### ISSUE THREAD

**Issue by santonelli** [plone/plone.app.layout#235]
Due to #2967 we have to update the markup of the templates listed below. 

- [x] plone.app.layout.viewlets.document_byline.pt
- [x] plone.app.layout.viewlets.globalstatusmessage.pt
- [x] plone.app.layout.viewlets.path_bar.pt
- [x] plone.app.layout.viewlets.searchbox.pt
- [x] plone.app.layout.viewlets.sections.pt
- [x] plone.app.layout.viewlets.footer.pt
- [x] plone.app.layout.viewlets.keywords.pt
- [x] plone.app.layout.viewlets.document_relateditems.pt

Feel free to add missing templates here. See also #3061 for further details. Check overrides in [plonetheme.tokyo](https://github.com/collective/plonetheme.tokyo) for already existing updated templates.

**Comment by fredvd** [comment]
@santonelli @agitator AFAICS this ticket was just not updated yet, but the not checked templates for keywords and sections.  were already added and bootstrapped. 

And as discussed on the sprint meet wednesdaymorning @santonelli had something already prepared to split up the document_byline.

**Comment by agitator** [comment]
Todo: Update status messages
- default in this package
- all others in various packages

States:
- info
- warning
- error

Look:
- add icon
- add colon to msg type

<img width="554" alt="Screenshot 2021-01-12 at 16 36 26" src="https://user-images.githubusercontent.com/365761/104336159-69e06880-54f4-11eb-8473-b796a5bd6a06.png">

**Comment by jensens** [comment]
I fixed the statusmessage default in this package to look like above.

**Comment by santonelli** [comment]
All templates has been touched. Bugfixes are welcome.
