### ISSUE TITLE
membertools.pt: dropdown menu doesn't work in barceloneta lts branch

### ISSUE THREAD

**Issue by phgv** [plone/plone.app.layout#248]
The dropdown user menu doesn't work when Toolbar is not visible to Authenticated user

**Error** (browser console) : Uncaught DOMException: Document.querySelector: 'http://localhost:8080/Plone/useractions' is not a valid selector

**Versions**
- Plone 6.0a1.dev0 (6000)
- CMF 2.4.9.dev0
- Zope 5.0
- Python 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
- PIL 6.2.2 (Pillow)
- WSGI: On
- Servidor: waitress 1.4.4

**Comment by petschki** [comment]
I think this got fixed.
