### ISSUE TITLE
media-object from BS4

### ISSUE THREAD

**Issue by yurj** [plone/plone.app.layout#272]
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/document_relateditems.pt#L17

Hi! this is Bootstrap 4, should be converted to BS5 because media-object classes are not available in BS5. Luckly, BS5 provides a way to do it:

https://getbootstrap.com/docs/5.1/utilities/flex/#media-object

```html
<div class="d-flex">
  <div class="flex-shrink-0">
    <img src="..." alt="...">
  </div>
  <div class="flex-grow-1 ms-3">
    This is some content from a media component. You can replace this with any content and adjust it as needed.
  </div>
</div>
```

**Comment by agitator** [comment]
yes, this was done in the process before we switched to bs5.
These are exactly those things that one see's while actually testing out and why it is so important to start using it.
prs are very welcome ;-)

**Comment by yurj** [comment]
for reference, also an horizontal card can be an easy drop-in:
https://getbootstrap.com/docs/5.1/components/card/#horizontal

I hope to make some work and a PR asap

**Comment by agitator** [comment]
also for reference, we decided to not overstyle plone specific components too much to allow easier project specific styling ;-)

**Comment by yurj** [comment]
@agitator can we close it?
