### ISSUE TITLE
Navigation items are double escaped when rendering an error view

### ISSUE THREAD

**Issue by thomasmassmann** [plone/plone.app.layout#280]
This bug was introduced in plone.app.layout with this commit: https://github.com/plone/plone.app.layout/commit/a62ae1436e5935159d43171168f5539000d2a65f

The title for action items need to be escaped to prevent XSS attacks. But the escape function is applied in the render_item method. This method gets the item and modifies it! This is no problem for a normal request, where it happens once per item.

But whenever an error occurs, the navigation is rendered (first iteration, item titles are escaped), then the error happens and the error view is rendered and with it the navigation items (again).

Now the navtree method is memoized, so it is still available, with the already escaped item titles. But now the items are rendered again, and so the titles are escaped a second time.

## Possible solution

Instead of escaping the item titles in the render method, they should be escaped in the navtree method (which is memoized):

```diff
    @property
    @memoize
    def navtree(self):
        ret = defaultdict(list)
        navtree_path = self.navtree_path
        for tab in self.portal_tabs:
            entry = tab.copy()
            entry.update(
                {"path": "/".join((navtree_path, tab["id"])), "uid": tab["id"],}
            )
            if "review_state" not in entry:
                entry["review_state"] = None

            if "title" not in entry:
                entry["title"] = tab.get("name") or tab.get("description") or tab["id"]
            else:
                # translate Home tab
                entry["title"] = translate(
                    entry["title"], domain="plone", context=self.request
                )

-            entry["title"] = safe_unicode(entry["title"])
+            entry["title"] = escape(safe_unicode(entry["title"]))
# ...
        for brain in brains:
            brain_path = brain.getPath()
            brain_parent_path = brain_path.rpartition("/")[0]
            if brain_parent_path == navtree_path:
                # This should be already provided by the portal_tabs_view
                continue
            if brain.exclude_from_nav and not context_path.startswith(brain_path):
                # skip excluded items if they're not in our context path
                continue
            url = brain.getURL()
            if brain.portal_type in types_using_view:
                url += "/view"
            entry = {
                "id": brain.getId,
                "path": brain_path,
                "uid": brain.UID,
                "url": url,
-                "title": safe_unicode(brain.Title),
+                "title": escape(safe_unicode(brain.Title)),
                "review_state": brain.review_state,
            }
            self.customize_entry(entry, brain)
            ret[brain_parent_path].append(entry)

    def render_item(self, item, path):
        sub = self.build_tree(item["path"], first_run=False)
        if sub:
            item.update(
                {
                    "sub": sub,
                    "opener": self._opener_markup_template.format(**item),
                    "aria_haspopup": ' aria-haspopup="true"',
                    "has_sub_class": " has_subtree",
                }
            )
        else:
            item.update(
                {"sub": sub, "opener": "", "aria_haspopup": "", "has_sub_class": "",}
            )
-        if "title" in item and item["title"]:
-            item["title"] = escape(item["title"])
-        if "name" in item and item["name"]:
-            item["name"] = escape(item["name"])
        return self._item_markup_template.format(**item)
```

@mauritsvanrees, you added the changes from the security fix. What do you think about this?

**Comment by thomasmassmann** [comment]
The result of double-escaped items:

`Examples & Demos` becomes `Examples &amp; Demos`

**Comment by mauritsvanrees** [comment]
It took me a while to see how to reproduce this. At first I tried with a ZMI script which raises an error. But this does not already render the navigation for the first time, so it goes fine. Key is to add an error in a template, so that the navigation is rendered once fine, and then an error happens, and it gets rendered again.

What I settled on:
- Create a Plone site (tried on 5.2).
- In portal_view_customizations customise `document_view` and add `<span: tal:content="python:1/0" />` within the `content-core` macro.
- Create a folder Cops & Robbers.
- Within this folder, add a page (no ampersand needed).
- Visiting the page throws a ZeroDivisionError and in the global dropdown menu you see `Cops &amp; Robbers`.

Your change helps, so I would welcome a PR on 3.x and master.
Do add the handling for `item["name"]` as well though, please. I don't know from the top of my head where this is used though.

**Comment by thomasmassmann** [comment]
Ok, I’ll add the PR

**Comment by thomasmassmann** [comment]
@mauritsvanrees , what about the master branch for 4.x?
