### ISSUE TITLE
plone.portaltop and plone.portalheader viewlets situation

### ISSUE THREAD

**Issue by erral** [plone/plone.app.layout#286]
We have seen this many times in our projects and I was hit by this last week so I decided to report it.

In Plone's `main_template.pt` there is a viewlet manager in use called `plone.portaltop` and included directly there, see:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/main_template.pt#L58

If you check its registration in this plone.app.layout package, you can check that, *by default* there is only one viewlet registered to appear there, the viewlet `portal.header` here:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L140

As you can see in that registration, that viewlet just includes another viewlet manager called `plone.portalheader`, see:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/portal_header.pt

And this viewlet manager is the one where some more default viewlets are registered into such as the [plone.searchbox](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L156) the [portal.anontools](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L164) the [portal.membertools](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L173) or [plone.logo](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/configure.zcml#L182). Even plone.app.multilingual registers the [language change viewlet in plone.portalheader](https://github.com/plone/plone.app.multilingual/blob/master/src/plone/app/multilingual/browser/configure.zcml#L199)

The point here is that if you need to override the internals of any of those viewlets for some reason (in our case we need to almost always override the language change viewlet) you need to be very careful because the `view` attribute of the viewlet is not anymore the `view` that is being rendered but the `plone.portaltop` viewlet. I think that this happens because of the double indirection of the "viewlets are registered to be shown in a viewlet manger that is shown through a viewlet in another viewletmanager".

I haven't done any tests but I think this can be easily resolved removing the `plone.portaltop` viewlet manager from the `main_template.pt` and replacing it with the contents of the actual `portal_header.pt` and thus including the `plone.portalheader` viewlet manager there. And of course changing any other registration that might happen in Plone's codebase from `plone.portaltop` to `plone.portalheader`. 

I even think that it simplifies a bit Plone's main_template and viewlet story.

I can't recall any historical reason why we have this like this in Plone.

Any thoughts?

**Comment by yurj** [comment]
With Diazo, this registrations are just a way to group things logically. The main feature of the viewletmanager today is the ordering, which let you move things without any coding.

For example, to have a list of link over the header in a viewlet, registering it as plone.portaltop viewlet has been very handy. This is my little experience.

**Comment by agitator** [comment]
Never understood that either... and wondered why it is that way...

I'd untangle them too, just have them as two separate viewlet managers

- plone.portaltop
- plone.portalheader
- ... 

Now is the time for it ;-)

**Comment by iham** [comment]
i remember those made sense ... ages ago... i guess good ol' plone 4 times and heavy float layout nesting.

let's consolidate them and remove that double nesting and use the default name schema "plone.<name>" for the viewletmanagers.

**Comment by erral** [comment]
I created the 3 referenced PRs. I am not exactly sure whether we need the upgrade step... I have never really make `viewlets.xml` work. I always ended going to `@@manage-viewlets` 😇

**Comment by Rudd-O** [comment]
I generally use Python code in my policy products to manage viewlets.  That works fine.

**Comment by erral** [comment]
Can someone review the PRs or at least comment on the approach? Thx.

**Comment by Rudd-O** [comment]
So, we remove `plone.header` in favor of `plone.portalheader`, if this is correct then the PRs (all of them) look good to me.
