### ISSUE TITLE
Should not use 'structure' for status messages

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.layout#297]
We cannot be sure that the status messages are safe to display as raw html value. Might be fine for core Plone, but perhaps not for all add-ons or custom code.
This was introduced in commit b86b546c4eb524e020dd4a731ef44dc576e861da last year for the Barceloneta LTS Changes.

We *could* introduce a keyword argument `safe` when adding a status message. Would be False by default. If you want to insert raw html, and are sure no user-supplied data is included, you could pass value True.

But for now let me remove `structure` here.

@santonelli Do you know a case in core Plone where we currently need the raw html? That should be fixed then, otherwise it will look ugly after I remove this.

**Comment by yurj** [comment]
I think that we should provide an api to sanitize (based on context like url, html, js, etc) text to be exposed. If TinyMCE does it for html, then we should use the same transform for statusmessage.
