### ISSUE TITLE
Hard to customize scale used for social images

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.layout#323]
Since this commit 4fb6bd2691c7f5ff607ddc7d2ab0cde684cf5e9f, it is even harder than before to use a custom scale in social tags images urls :
https://github.com/plone/plone.app.layout/blob/5478b8ff1672cf553416cd9ab7e6f99852914103/plone/app/layout/viewlets/social.py#L99

To avoid having to override 100+ lines of code to do just this, we propose to use a simple variable outside the method.

**Comment by jensens** [comment]
This is fine IMO, You could go the complex path with a setting in the control panel as well, but maybe overkill.
