### ISSUE TITLE
Nested li-s in contentviews.pt

### ISSUE THREAD

**Issue by erral** [plone/plone.app.layout#346]
The contentviews.pt viewlet has a nested li see:

https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/contentviews.pt

```
  <li class="border-top my-2">

    <tal:contentmenus>
      <div tal:replace="structure provider:plone.contentmenu"></div>
    </tal:contentmenus>

    <li class="border-top my-2">

      <tal:block define="
                   actions view/tabSet2;
                 ">
        <div tal:replace="structure python: view.menu_template(actions=actions)"></div>
      </tal:block>

    </li></li>
```

Do we need this? I have seen this when extracting strings for PO files.

@gforcada you were the last one touching the file when running zpretty, any hint here?

**Comment by gforcada** [comment]
No idea, I only ran `zpretty` on it, but I guess it only checks for the consistency not its validity.

Is there any tool that checks such things? 🤔 

@petschki could it be that this was introduced in your https://github.com/plone/plone.app.layout/commit/b859dafea3f16ec6f08301b2cdefaf25a40217d3 (in https://github.com/plone/plone.app.layout/pull/254)?

**Comment by petschki** [comment]
my commit https://github.com/plone/plone.app.layout/commit/b859dafea3f16ec6f08301b2cdefaf25a40217d3 misses closing `</li>` tags for the separator lines ... but after `zpretty` those closing tags are added at the end ... that's bad ... I suggest to fix this in #349

**Comment by petschki** [comment]
> Is there any tool that checks such things? 🤔

We could implement our own `lxml-pre-commit-hook` in plone/meta ... found some examples here https://github.com/Lucas-C/pre-commit-hooks-lxml/tree/master/pre_commit_hooks

**Comment by gforcada** [comment]
@petschki cool that's nice, let's create an issue so we don't forget: https://github.com/plone/meta/issues/153
