### ISSUE TITLE
root.getNavigationRootObject should take care of temporary objects

### ISSUE THREAD

**Issue by keul** [plone/plone.app.layout#57]
Found debugging issues with archetypes.multilingual.

Whe you call getNavigationRootObject(document) where document is a temporary object, that navigatioRoot returned is always the Plone site even if you have a navigation root (like a language folder under the root).

IMO the method should check for temporary object.

This probably affects Plone 4 and Plone 5 also

**Comment by naro** [comment]
Weird, I'm trying to sort the same issue with a.multilingual for a site migrated from Plone 3.1.7 I'm using 
```
[sources]
plone.app.multilingual = git https://github.com/plone/plone.app.multilingual branch=fix-archetypes-multilingual-issue-13
archetypes.multilingual = git https://github.com/plone/archetypes.multilingual branch=fix-issue-13
```
but the error persists so I dig into pdb and get_language code...
```
(Pdb) l
 19  	        portal_factory = getToolByName(self.context, 'portal_factory', None)
 20  	        if portal_factory is not None and portal_factory.isTemporary(self.context):
 21  	            # This should probably be fixed in plone.app.layout getNavigationRootObject
 22  	            # Right now navigation root of a temporary object is Plone site due to acquisition
 23  	            # https://github.com/plone/plone.app.layout/issues/57
 24  ->	            context = self.context.aq_parent.aq_parent.aq_parent
 25  	            navroot = getNavigationRootObject(context, getSite())
 26  	            if navroot != self.context:
 27  	                try:
 28  	                    lang_info = ILanguage(navroot)
 29  	                    language = lang_info.get_language()
(Pdb) self.context
<Window at /irel/irel/en/journals/portal_factory/Window/window.2015-11-07.6495835664 used for /irel/irel/en/journals>
(Pdb) getNavigationRootObject(self.context, getSite())
<Container at /irel/irel/en>
(Pdb) getNavigationRootObject(self.context.aq_parent.aq_parent.aq_parent, getSite())
<PloneSite at /irel/irel>
```
As you can see, the ```getNavigationRootObject(self.context, getSite())``` call is correct so it is not necessary to use aq_parent three times, moreover it returns wrong result :( 

This is how getNavigationRootObject processes the context object (print at the beginning and then print parent inside the loop)
```
<Window at window.2015-11-07.6495835664>
<Products.CMFPlone.FactoryTool.TempFolder object at 0x10c5e7e60>
<FactoryTool at portal_factory>
<ATFolder at journals>
<Container at en>
```
so it looks correct to me. 

I would say p.a.layout is fine.

**Comment by keul** [comment]
@naro unluckily I'm not working anymore for the customer where I reproduced this issue and I don't have the development environment anymore.

Feel free to close the issue!
