### ISSUE TITLE
GlobalSectionsViewlet current tab selection problem and plone.app.multilingual

### ISSUE THREAD

**Issue by diti76** [plone/plone.app.layout#68]
Hi PloneDev, there is a strange behaviour/(bug?) in the GlobalSectionsViewlet class. 
The problem occurs when plone.app.multilingual  is enabled. What happens is that the selected tab is not recognized correctly. Please see http://pastie.org/10484537 line 34 (my comment), to understand what I mean. 
changing line 34
if action_path_list[1] == path_list[1]
to
if action_path_list[2] == path_list[2]
solved the issue... but I don't know if it is the best solution, might not work when not using plone.app.multilingual

**Comment by tomgross** [comment]
Hi @diti76 can you confirm https://github.com/plone/plone.app.layout/pull/69 fixes your issue?

**Comment by diti76** [comment]
I just tried it now. I can confirm that the issue has been solved.
Thanks!
