### ISSUE TITLE
Body class pat-markspeciallinks not set

### ISSUE THREAD

**Issue by ukretschmer** [plone/plone.app.layout#84]
The pattern class for markspeciallinks isn't set in body classes. The reason seem to be the condition in [layout.py](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/globals/layout.py#L268): 

`if msl == 'true' or elonw == 'true':`

should be simplified to

`if msl or elonw:`

Datatype of according registry settings is Boolean not String.

**Comment by thet** [comment]
Fixed with referenced commit. Thanks for reporting!
