### ISSUE TITLE
Base tag differs from actual URL

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.layout#86]
This is a 12 year-old bug migrated from: https://dev.plone.org/ticket/2988

Just to keep it clear: the HTML `<base>` element specifies the base URL to use for all relative URLs contained within a document.

There are 3 different cases that need to be tested:
1. folderish item with no default page defined: base tag and URL are the same
2. folderish item with default page defined: base tag and URL must be the same (this is the actual issue here)
3. any other item: base tag and URL are the same

**Comment by rodfersou** [comment]
Addin an extra use case:

4. default page object: URL should be the object URL

**Comment by seanupton** [comment]
@hvelarde @rodfersou is this Plone 4 only?

I have another use case to add: base tag on edit forms (both Archetypes and Dexterity) in Plone 4 does not include the /edit portion of the URL, which breaks correct URL for page refresh when one is using the autotoc pattern from plone.app.widgets 1.x for form tabbing.

In my case, I verified in pdb that the edit form base tag is broken by ZPublisher.BaseRequest.BaseRequest.traverse() [calling](https://github.com/zopefoundation/Zope/blob/c233041e8beea1527216ed447cc065f1601a3834/src/ZPublisher/BaseRequest.py#L501) ZPublisher.HTTPResponse.HTTPResponse.setBase() without the complete URL.

Here is what I have found so far in debugger:

1. "Hacked URLs" are affected;
2. I suspect this includes any use of alias to browser views, e.g. /edit -> /@@edit
3. I suspect this includes any use of alias to another skin-based callable, e.g. /edit -> /atct_edit
4. I would assume that default pages are the same sort of situation, but have not verified.

My hunch on the way forward is a case-by-case application of post-traversal hook for the  (four) use cases I see here.  Thoughts?

**Comment by rodfersou** [comment]
@plone/framework-team New Pull requests for Plone 4.3.x:

* https://github.com/plone/plone.app.layout/pull/87/files
* https://github.com/plone/Products.CMFPlone/pull/1710/files

Jenkins job: http://jenkins.plone.org/job/pull-request-4.3/348/console

Already Green

**Comment by hvelarde** [comment]
@seanupton yes, this is for Plone 4 only; base tag was already removed in Plone 5.

**Comment by seanupton** [comment]
@rodfersou good to know about...

I have started [discussion about what risks might be for backporting](https://community.plone.org/t/base-tag-in-plone-4-edit-forms-archetypes-and-dexterity/2588) Plone 5's more aggressive approach to `<base>` tag removal, and what that might break.  I really would like to fix this for edit forms, too.

**Comment by rodfersou** [comment]
@seanupton I agree with you that backporting Plone 5 approach would be better, but we can do it in a second step.  I think we can get some Javascript problems where it looks the ``<base>`` tag.

We are already using the approach in this pull request into www.brasil2016.gov.br site with a monkey patch.

**Comment by seanupton** [comment]
@rodfersou -- yeah, running this will show trouble is scattered in many places:

`omelette sean$ grep -r '$(.base.)' *`

...but I wonder about:

1. Stripping tag like Plone 5;
2. JS shim in main template:
```javascript
(function () {
  "use strict";

  var head = document.getElementsByTagName('head')[0],
      existing = head.getElementsByTagName('base'),
      base = document.createElement('base');
  if (existing.length) {
    head.removeChild(existing[0]);
  }
  base.setAttribute('href', window.location.href);
  if (head.firstChild) {
    head.insertBefore(base, head.firstChild)
  } else {
    head.appendChild(base);
  }
}());
```

My sense is that this is appropriate for a policy product, not likely appropriate for integrating into Plone 4 core packages (including optional ones like plone.app.widgets 1.x). Part of this is that getting order right in the Plone 4 JS registry is a pain, and overriding main_template as I am proposing is a hacky task of integration (though this could be done with a viewlet).

**It is possible that step 2 above makes step 2 unnecessary.**

**Comment by rodfersou** [comment]
@seanupton how about to merge this pull request as it is, and open a new issue to remove ``<base>`` tag definitely?

As @hvelarde said before, it is a 12 years old issue.. I would like to fix it ASAP :smile:

**Comment by seanupton** [comment]
@rodfersou agree with strategy, nothing I would do to transform base client side is incompatible with your approach, and your approach solves a common problem.

While I do not think I am the best resource to review and merge #87, I just replied to the community thread advocating that folks review and merge your PRs.

**Comment by rodfersou** [comment]
@seanupton nice, thank you for your help

**Comment by rodfersou** [comment]
pull requests merged :clap:
